### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by nina2728** [nina2728/furima-34709#9]
# URL
https://furima-34709.herokuapp.com/
# Basic認証ID,PASSWORD
ID:nina
PASSWORD:34709
# ユーザーA
email:a@a
password:aaa111
# ユーザーB
email:b@b
password:bbb111

**Comment by snkw-works** [comment]
@nina2728 さん、お待たせいたしました。ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下、ご確認をお願いします！

[修正依頼箇所]
- [ ] **商品出品にて、販売価格は、¥300~¥9,999,999の間のみ保存可能であるよう修正しましょう**
9999999円での出品ができない状態です。

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by snkw-works** [comment]
@nina2728 さん、お待たせいたしました。ご提出ありがとうございます‼︎
修正が確認でき、問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/121793497-8ebf4000-cc3a-11eb-962b-c7d53d208701.png)
